### ISSUE TITLE
关于使用pylatex中 编译的问题

### ISSUE THREAD

**Issue by royccg** [tczrr1999/PyTex#4]
您好，我使用 pylatex --version(1.3.4)中，
想在`doc.generate_pdf`中进行两次`xelatex`编译
但是不知道怎么添加 `compiler_args`参数。
想问下，大佬，能实现吗？

**Comment by zrr1999** [comment]
pylatex在第一次编译之后会直接跳出循环，要是想编译两次可以写两个doc.generate_pdf。因为我也没研究透源码所以有可能有我没发现的方法，你可以去pylatex项目问一下。我最近在写一个新的简化框架，写的时候会考虑这个问题。

**Comment by royccg** [comment]
ok，感谢！
