### ISSUE TITLE
pypi.org / texdown?

### ISSUE THREAD

**Issue by nschloe** [tczrr1999/PyTex#6]
Hi!

Is this the GitHub repository with the pypi package [_TeXDown_](https://pypi.org/project/TexDown/)? If yes, I would like to ask if said package is still maintained. If not, I'd be happy if you could remove it from pypi. (I have a package in the pipeline that goes by the same name.)

Cheers,
Nico

**Comment by zrr1999** [comment]
ok

**Comment by nschloe** [comment]
Thanks!
